// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;
import "./ERC721S.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/finance/PaymentSplitter.sol";

/*

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXXK00OOkxxxdddddoooooddddddxxkkO00KXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0Okxdolc:;,,'..............    .  ............'',;:clldxkO0KXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOkdoc:,'......          ..    ....                       ..   ......,;cldxOKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxol:,.....  ..                                                                ....,;coxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXOxoc,'...  .   ....                                                                     ..  ....,:ldkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOdl;'..  .. ..  .     ..                                                                    ..   ..     ...;cdkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxl;'....     ..    ..  .       ..         ..      .                     ..   .               .....   ..   ..    ....;cdOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKko:'...   .           .. ...   .    .  .   .   ........'',,,,,;;;;;;,,,,,'........     ..      ..    ...   .               ..';lx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKko:'..   ...                 ....  . .......',:cloddxkO00KKXXNNNNNNWWWNNNNNNXXKK00Okxddolc:;,......   .  .. ...                 ......;lkKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOd:'...    . ..            .   ..  ....,;cldxO0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0Oxdoc;,....  .                  ...  .  ...;oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxl,... .  .     ..       ..  .  ...,:ldxOKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNK0kdl:,...      ..  .   ..  .    ..  ..'cx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0x:'......       .   .    .   ...,:ldOKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxo:,.... ..  .  .    ....       ..;oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d:..   ..  .            .   ..,cok0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkoc,....  .. .   .           ...;oONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:..  .  .  ..            ..':lx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKko:'.. . ..            .. ....;o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkc'.   .    .  ...  .    ..':okKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc,.... .  .     . ..  .  ..:xKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0o,.......    . ..    . ...;okKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0kdlc:;,,,,,,,,;::codk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOd:'..        .       .  ..'ckXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:...  ...      .  ..  ..,cxKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdl;'... ..              ...':lx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl;..    .          ..  ..;o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl'....   .         .. ..;oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl,..  ...  ..          .  .....  ..;oONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0d:.. ..         .      ..ckXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx:..   .            ....;o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkc'..   .  .   .        ....  .  .  ..  ..,o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKx:'.. .   ....    . .. .;dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd,.              ..  ..;d0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;...                ...     .    ..        ...:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:.. .  ....    .    ..'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo,...        ..    ...;oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd,.                    ..........  .....       .  .:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d;.. ...   ....    . .'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'..  .      ....   .'cONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;. .                   .  ....    ...  ....         ..l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl'..   .   .....  . .'l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'.  ...  .  . ......;dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl.. ..   . ..  ..   ....',;:::::;,'... ..  ..  ..     . .,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:.. ..   .   ...   .'l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd,.  ......   ..  ...ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:. . .. .     .  ...,cdO0XNWWWWWWWNK0kd:'.. . ..         ...oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl'...  . .        ..'lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx,.    ....      . .'l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;. .  .     .... .,lOXWMMMMMMMMMMMMMMMMMWKkc'. ..          ...lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd,.  ..     . .. . .'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNO:. .   ...        .,dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:.  ..  .. .    .;xXWMMMMMMMMMMMMMMMMMMMMMMMW0o'..         .   .lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx;..   .   .  .  . .,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l..  .  ...  .   ..;dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc.         .  ..'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.   ..    .... .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx;. .. .      ..   .:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo'.         . .   .,xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.          .  .,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.    ..  .    .,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;.. .  .  .  .   ..lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;.  .      ... ...,dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;. .          .,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd..  .  ..  .  .lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx;... .    .   .  .,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl..        ..... .'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx...          ..xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc. .  .   .    ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx,.  .  .... .   ..:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk,. .   .  . ..  ..l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl. ..         .:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'.  ..  ..  . .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl....   .. .   . .'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.......        ..:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc. ..         .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;   .  .    . .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:.. ..          ..:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWO:......    ..   .'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:..  .        .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:..     .    ..oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,...        ..  .,xNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMNx'.   .        ...:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc..  .        .lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;...      ..  .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl..        .   ...oXMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMXo..           . .'dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.....        .;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'...  .      ..xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;. ..      . .. .:0MMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMKc.   ...        .:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.....         .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:. .. ..   .  .;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl..  .         ..;OWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWO;.    .   .    .'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:....       .  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl. ..  .. .. . .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,..  .         .'xWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWk,.  .    ... ...;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.  .       .  ..dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl. .      .    .;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:.            ...dNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNx'. ..     .  ...cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl. .         .  .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;..  ..  .  .  ..xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.. .  .      ...oXMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMNd...        .. ..oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:.        ..    .'l0WMMMMMMMMMMMMMMMMMMMMMMMNkc.. .           ..oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'... .    .    .lXMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNd...         . .'dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:.             ....cxKNWMMMMMMMMMMMMMMMWNOo;....  .        ...oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,..   .       ..lXMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNd..            .,kWMMMMMMMMMMMMMW0dddooddddddddddddddddddddddddddddddddddddddddddddddddddddddddooddoo:.         ..       ..;xNMMMMMMMMMMMMMWk;.. .  . ..       ...'loddddddddddddddddddddddddddddddddddddddddddddddddddddddddddoddooddxKWMMMMMMMMMMMMMWO;. .   .  .   ..lXMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNd.. ..   ..    .;OWMMMMMMMMMMMMMNx'. ..                                                           .   .          ...      ...cXMMMMMMMMMMMMMNo...  .   ..         . .                                                                 ..;OWMMMMMMMMMMMMMM0:..     .  .  ..lXMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWx'.  ..  .     .;0WMMMMMMMMMMMMMXo..                                                                                       ...:XMMMMMMMMMMMMMNo.                                                                                         .'xNMMMMMMMMMMMMMMK:.             .oNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWk'..       ..  .;0WMMMMMMMMMMMMMKc...  ..                                                                                   ...:XMMMMMMMMMMMMMNo.                                                                                          ..dNMMMMMMMMMMMMMMK:.             .dNMMMMMMMMMMMMMM
MMMMMMMMMMMMWO,.  .    .    .;0WMMMMMMMMMMMMWK:.  ... ..                                                                                  ...:XMMMMMMMMMMMMMNo.                                                                                         . ..oXMMMMMMMMMMMMMMK:..           ..xNMMMMMMMMMMMMM
MMMMMMMMMMMM0;. ..    .   ..,OWMMMMMMMMMMMMW0;. .. .  .                                                                                ..   .cXMMMMMMMMMMMMMNo.                                                                                          .  .lXMMMMMMMMMMMMMM0;.       .    .'kWMMMMMMMMMMMM
MMMMMMMMMMMXc.            .'kWMMMMMMMMMMMMW0;.                                                                                         ..  ..cXMMMMMMMMMMMMMNo...                                                                                           ..lXMMMMMMMMMMMMMWO;.   ..    .. .;0MMMMMMMMMMMM
MMMMMMMMMMNo.            ..xWMMMMMMMMMMMMMNd;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;dNMMMMMMMMMMMMMWx;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;:kWMMMMMMMMMMMMMWk'..   ...   ...lXMMMMMMMMMMM
MMMMMMMMMWk'....         .oNMMMMMMMMMMMMMMWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNWMMMMMMMMMMMMMMMNd. .. ..     . .dWMMMMMMMMMM
MMMMMMMMMK:. ..  ..  .  .cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl. .   .  .  ..,0MMMMMMMMMM
MMMMMMMMNo...   ..  .  .,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:.   .        .lXMMMMMMMMM
MMMMMMMWk'.  .   .   ...dWMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMWk'.. .         .xWMMMMMMMM
MMMMMMMXc..  ...   . ..cXMMMMMMMMMMMMMKo:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::cOWMMMMMMMMMMMMNd.  ..        .:KMMMMMMMM
MMMMMMWx..      .  . .,OMMMMMMMMMMMMMNl.                                                                                                                                                                                                                           .;0MMMMMMMMMMMMMX:...         ..dWMMMMMMM
MMMMMMK:. .  .    .. .oNMMMMMMMMMMMMWx'                                                                                                                                                                                                                             .lNMMMMMMMMMMMMWk'           ..;0MMMMMMM
MMMMMWx.     .. ..  .;KMMMMMMMMMMMMM0;.                                                                                                                                                                                                                              'kWMMMMMMMMMMMMNl.            .dWMMMMMM
MMMMMXc.   ..     ...dWMMMMMMMMMMMMNo..                                                                                                                                                                                                                         ..  ..:KMMMMMMMMMMMMMO,            .;KMMMMMM
MMMMMO'.    .    . .;KMMMMMMMMMMMMMO,.         .  .  .                                                                                    ..  .             .  .                                                                                          ..  ... .. ..xWMMMMMMMMMMMMNl.           ..dWMMMMM
MMMMNo.          . .dWMMMMMMMMMMMMNl.          ................................................................................................         .   ...............................................................................................    ..   ...;KMMMMMMMMMMMMWk'.         . .:KMMMMM
MMMMK;.          ..,0MMMMMMMMMMMMMO'..         ..ckkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkc..            .ckkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkl... .. .. .  .dWMMMMMMMMMMMMXc.        .  .'OMMMMM
MMMWx.         .  .lNMMMMMMMMMMMMNo.  .        .,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.           . .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc...  ..  . ..:XMMMMMMMMMMMMWd.            .oWMMMM
MMMNl.          . .xWMMMMMMMMMMMM0;.. .. .   . .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.            ..dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx..   .     ..'kMMMMMMMMMMMMM0,.     .  .. .:XMMMM
MMMK;.          ..;KMMMMMMMMMMMMWx. ..    .. ..,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.           ...dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;.           .lNMMMMMMMMMMMMNl. .  ..  ..  ,OMMMM
MMMk'..        . .lNMMMMMMMMMMMMNl..    .  . ..cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkxxxxxxxxxxxxkKWMMMMMMMk.           ...dWMMMMMMMXkxxxxxxxxxxxxkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.           .:KMMMMMMMMMMMMWd.....       ..xWMMM
MMWd...        . .xWMMMMMMMMMMMM0;. ..   .  ...dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'.............dWMMMMMMMk.           ...dWMMMMMMWk'.............dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'..          'OMMMMMMMMMMMMMO' ...  .     .oNMMM
MMNl..          .,OMMMMMMMMMMMMWk. ..     ..  ,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'..          .dWMMMMMMMk.           ...dWMMMMMMWk' .          .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:.  .        .dWMMMMMMMMMMMMK;. ..    .  ..:XMMM
MMX:..          .;KMMMMMMMMMMMMWo.  .   .  ...:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'..          .dWMMMMMMMk.           ...dWMMMMMMMk'..          .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo. ..       ..lNMMMMMMMMMMMMXc...     .  ..;0MMM
MMK;.           .cXMMMMMMMMMMMMNc.  .  .    ..lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'..          .dWMMMMMMMk.           ...dWMMMMMMMk'..          .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx..         ..:KMMMMMMMMMMMMNl..   ..    ..'OMMM
MM0,.           .lNMMMMMMMMMMMMK:.   .       .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'..          .dWMMMMMMMk.           ...dWMMMMMMMk'..          .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'.           ,OMMMMMMMMMMMMWd.  .  . .    .xMMM
MMO'.           .oNMMMMMMMMMMMM0; .  .  .  . .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;  .         'kMMMMMMMMMMMMMk.     .      .dWMM
MWk' ..         .oWMMMMMMMMMMMM0, .     .    'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;.           .xWMMMMMMMMMMMMk'         .  .dWMM
MWx..  .       ..dWMMMMMMMMMMMMO,            'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:.           .xWMMMMMMMMMMMMO'.     .  .  .oWMM
MWd..          ..dWMMMMMMMMMMMMO'   .        ,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:.           .xWMMMMMMMMMMMMO'   .  ..    .oWMM
MWx...          .dWMMMMMMMMMMMMO'.  ..   ..  ,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:..          .xWMMMMMMMMMMMMO'   .      . .oWMM
MWx...          .dWMMMMMMMMMMMMXxooooooooooooxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkooooooooooooxKMMMMMMMMMMMMMk'   .  .. .  .dWMM
MMk'            .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk. ..  .  .  ..dWMM
MMO, .         ..lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.  . ..      .xWMM
MM0,..          .cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.  ..   .    'kMMM
MMK;..          .:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl. .   .    ..,0MMM
MMXc.          ..,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc..          .;KMMM
MMNo. .          .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,.  ..       .cXMMM
MMWx.            .dWMMMMMMMMMMMMWNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMWx.     ..   . .dWMMM
MMMO,  .         .cXMMMMMMMMMMMMKl,,,,,,,,,,,,,,,,,,,,,,,,,,lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,,,,,,,,,,,,,,,,,,,,,,,,,,c0WMMMMMMMMMMMNl. .  .   .   'kMMMM
MMMX:.           .,OMMMMMMMMMMMMNl.   .                   ..;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc..               .....   .:KMMMMMMMMMMMMK;... .  .   ..;0MMMM
MMMWd.            .dWMMMMMMMMMMMMO'     .................  .;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc. .................    ...xWMMMMMMMMMMMWk...     ..  ..lNMMMM
MMMMO,            .:KMMMMMMMMMMMMXl. .. .........   .. .  ..;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc... ..............  .....cXMMMMMMMMMMMMNl..    ..     .xWMMMM
MMMMXc.         .. .kWMMMMMMMMMMMMO'.          ..   .   .. .;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc.     .             . ..'kWMMMMMMMMMMMM0,.       .  ..,0MMMMM
MMMMWx..           .cXMMMMMMMMMMMMNl.  .       ..  ....  . .;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc.  .  ..               .cXMMMMMMMMMMMMWd.        .  ..lNMMMMM
MMMMMK;.           .'OMMMMMMMMMMMMM0,. .       .    .. .   .;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc.   .  ..             .,OMMMMMMMMMMMMMK:.            'OMMMMMM
MMMMMNo.  ..   .    .lNMMMMMMMMMMMMNd.         .  ..:dddddddONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOdddddddc.          .  .oNMMMMMMMMMMMMWd.          ...lXMMMMMM
MMMMMMO,.. .  ..  .. 'OWMMMMMMMMMMMMK:.  ..    .  ..cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.        .. ..;0MMMMMMMMMMMMM0;.            'kWMMMMMM
MMMMMMNo.  ..  .     .cXMMMMMMMMMMMMWk'.         .. .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.           .'xWMMMMMMMMMMMMNo...         ..lXMMMMMMM
MMMMMMM0;..    . ..  ..xWMMMMMMMMMMMMNo..        . ...xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,..        .  .oNMMMMMMMMMMMMWk'.           .,OMMMMMMMM
MMMMMMMWd..  .      . .,OMMMMMMMMMMMMMXc...       .. .'xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;.    .       .:KMMMMMMMMMMMMMK:.     ..     .oNMMMMMMMM
MMMMMMMMK:.  .         .cXMMMMMMMMMMMMM0;.   .   ...  .,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;..  .    ..  .,OWMMMMMMMMMMMMNo. .   ..  .  .;0MMMMMMMMM
MMMMMMMMWk'.            .oNMMMMMMMMMMMMWO,. .     .... .,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;. .  .  .  ...'kWMMMMMMMMMMMMWk'. .         ..xWMMMMMMMMM
MMMMMMMMMNo.   .        .'kWMMMMMMMMMMMMWk'. .....   .. .,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;. .  . ..  . ..xWMMMMMMMMMMMMM0;... .. .  .  .cXMMMMMMMMMM
MMMMMMMMMMK:..          ..;0MMMMMMMMMMMMMWx' ..  ..      .'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,. ..    ..  . .dNMMMMMMMMMMMMMXc. . .   .. . .,0MMMMMMMMMMM
MMMMMMMMMMWO,.            .:KMMMMMMMMMMMMMNx...          ...dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'.        .  ...oNMMMMMMMMMMMMMNo.            .'xWMMMMMMMMMMM
MMMMMMMMMMMWx...         . .cXMMMMMMMMMMMMMNx...        .  ..lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd..          .. .oNMMMMMMMMMMMMMNd..          ...oNMMMMMMMMMMMM
MMMMMMMMMMMMNo.            ..lXMMMMMMMMMMMMMWx'.         ..  .:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKc..            ..dNMMMMMMMMMMMMMNx'.            .cKMMMMMMMMMMMMM
MMMMMMMMMMMMMXl.          .  .oNMMMMMMMMMMMMMWk,.      . .  . .,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;. .....  .  . .'xNMMMMMMMMMMMMMNx'..          ..;0WMMMMMMMMMMMMM
MMMMMMMMMMMMMMKc.. ..         .oNMMMMMMMMMMMMMWO;..        ......lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo..  ..    ..   .,kWMMMMMMMMMMMMMNx'.         . ..;0MMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMK:. . .    ..  ..oNMMMMMMMMMMMMMMKc..        ...  .;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:.   .   ..   ...:0WMMMMMMMMMMMMMNd..  .       ...,OWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMK:.... .    .   .lKMMMMMMMMMMMMMMXo..  .      .   ..lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo'. ..     .    ..lKMMMMMMMMMMMMMMNd....         ..,kWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMM0:.          . ..:0WMMMMMMMMMMMMMNk,.  .  ..      ..,xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;..  .      .  ..'dNMMMMMMMMMMMMMMXo...   ...     .,kWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM0:..            .;OWMMMMMMMMMMMMMW0c. .   . ..     ..;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:..  .         . .:0WMMMMMMMMMMMMMWKc..       .  . .,kWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMK:..          . .'xNMMMMMMMMMMMMMMNx'. ..  .      . ..cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l..  .         . .'dXMMMMMMMMMMMMMMWO;. .        .  .,OWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMKc..        .. ...oXMMMMMMMMMMMMMMW0c...  ...  .   ....c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl'. .  .         ..:OWMMMMMMMMMMMMMMNk,.  .       .  .;0WMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMXo...  .  .     ..cKWMMMMMMMMMMMMMMNx,... .  ..     . ..cONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l'.      .     .  .,dXMMMMMMMMMMMMMMMXo..     ..      .:0MMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNd'.   ..        .,kWMMMMMMMMMMMMMMWKl...... ..  .     ..:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl..   .....   .. ...c0WMMMMMMMMMMMMMMWO:..       ..  ...lXMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWk,...           ..oXMMMMMMMMMMMMMMMW0c.....   . .      ..;xKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx:..   . ...    .  ..:ONMMMMMMMMMMMMMMMXd'.  .         ...dNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMW0:. ..           .;OWMMMMMMMMMMMMMMMNO:..  .  .    .    ..'o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o,...  .  ..       ..;xNMMMMMMMMMMMMMMMW0:.       ..  . ..,kWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMKl.. .  . .      ..oKMMMMMMMMMMMMMMMMNk:.... .     .      ..:xKWMMMMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMWXkc'.    .  .        ..;xNMMMMMMMMMMMMMMMMXd'.    ..  ....  .:0WMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMNx,.. .  .  .   ...,xNMMMMMMMMMMMMMMMMNk:....    ..         .'ckXWMMMMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMMMMWXOl,.. ..         .. ...;xXMMMMMMMMMMMMMMMMWk;.  .          ...oXMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:.. .. .    .   ..:OWMMMMMMMMMMMMMMMMNOc.... . ..  .       ..,lkXWMMMMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMMMMWXOo,...    .      .. ....:kNMMMMMMMMMMMMMMMMWKl..            . .,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'..  .. ..     ...lKWMMMMMMMMMMMMMMMMN0l'.  ..   ...       ...,lxKWMMMMMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'            .dWMMMMMMMMMMMMMMMMMWKkl,..  ...   ..   .......cONMMMMMMMMMMMMMMMMWXd'.   ..         ..lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.. .   .     .  .'oKMMMMMMMMMMMMMMMMMWKd,..      .  .     .. ..':dOXWMMMMMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'        ..  .dWMMMMMMMMMMMMMWN0d:'..      ..  ..  .   ..,l0WMMMMMMMMMMMMMMMMMXx,.     ..   .  . .;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,.  .       .    .,dXMMMMMMMMMMMMMMMMMMNkc'.  .              .....,cdOXWMMMMMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'        ..  .dWMMMMMMMMMWN0xc,..        .  .  .   ....:xXWMMMMMMMMMMMMMMMMMNk;.          .  ...'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl.... ..          .,xXMMMMMMMMMMMMMMMMMMWKd;...  ...       .....  ...,cdkKNMMMMMMk'            .dWMMMMMMMk.           ...dWMMMMMMMk'        ..  .dWMMMMWNKkdc,... ..          . .... ..;o0WMMMMMMMMMMMMMMMMMMNk:.            .. ..c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:..  ..  .  ..  ...;dXWMMMMMMMMMMMMMMMMMMN0o;.. ..         ....  .   ...;ldkKXWk'            .dWMMMMMMMk.           ...dWMMMMMMMk'        ..  .dNX0kdc;... ..  ..             . ..,lONWMMMMMMMMMMMMMMMMMMXx;.     .       .. .;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;....  ... .  ..  .,o0WMMMMMMMMMMMMMMMMMMMNOl,.. .  .  .. .   ...   .  ....,:;.            .dWMMMMMMMk.           ...dWMMMMMMMk'         .  .,:,...    .  .   .        . . ..,lkXWMMMMMMMMMMMMMMMMMMWKd;.. . .  .   .    .'dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd,.  .. .   .....  .'lONMMMMMMMMMMMMMMMMMMMWXOo;..    ...                                 .dWMMMMMMMk.           ...dWMMMMMMMk'                                 .  .  ...;lkXWMMMMMMMMMMMMMMMMMMMN0l,.           ...  .'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd'.  .. ..    .    ..:xXMMMMMMMMMMMMMMMMMMMMMN0xc'... ..  ..                            .dWMMMMMMMk.           ...dWMMMMMMMk'                           .. ..   ...':d0NWMMMMMMMMMMMMMMMMMMMWXkc..             .  .'l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'....  ..    .  . ..,o0NMMMMMMMMMMMMMMMMMMMMMWXko;...  ..                            .dWMMMMMMMk.           ...dWMMMMMMMk'                         ..  .  ...;lkKWMMMMMMMMMMMMMMMMMMMMMW0d;...  .         . ..'l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo,...       .. . .. ..:dKWMMMMMMMMMMMMMMMMMMMMMMNKko:'..  .....               ...   .dWMMMMMMMk.           ...dWMMMMMMMk'          .    .    ..   .  ...;lkKNMMMMMMMMMMMMMMMMMMMMMMWXk:.. ...   .  .      .'l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd,.   .. .  .. ..  ...'cxKWMMMMMMMMMMMMMMMMMMMMMMMWX0xl;'.....  .  . ...   . ..   .dWMMMMMMMk.           ...dWMMMMMMMk'    .       ..    . ......,cdkKNMMMMMMMMMMMMMMMMMMMMMMMMXOl,...         .  ..  .'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx;...  .            ...'lkXWMMMMMMMMMMMMMMMMMMMMMMMMMNKOdc;'... ..         ..   .dWMMMMMMMk.           ...dWMMMMMMMk' ..       .    . ...';cok0NWMMMMMMMMMMMMMMMMMMMMMMMMWNOo,.... .         .  ...,dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc.... .  .  .  . ...  .,cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kdl:,.....  ...    .dWMMMMMMMk.           ...dWMMMMMMMk'       .......,:lok0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo;..  ..  .          ...:kXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o,....  ..  ..   .    ..':d0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxdlc;,'...  .dWMMMMMMMk.           ...dWMMMMMMMk'......,;cldkOKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKxc,..  .  ..       .    .'lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkc'. .... .. .        ....;oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNX0OxdllOWMMMMMMMk.           ...dWMMMMMMM0lloxk0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo:..              .    ...:xKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;...  .  .         .   ..':okKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMk.           ...dWMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc'..          .  ... .. ..,o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo,...              ..    ..':okKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.           ...dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOd:'..  .   .       .  . ....'lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl,..   . .  .  .. ..    . ...;lxOXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.           ...dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xl:'.. .   ..   ..     .   ...'cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl,..  ...  .   ...         ...';ldOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.           ...dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxl:,..               ..  ..  ...'cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo;....       ..        .. ..  ...,:ldk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMk.           ...dWMMMMMMMMMMMMMMMMMMMMMMMMMMWXKOxo:,...   ..                   ....,lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xc,..    ..        .  ....     . ...';coxk0KNWWMMMMMMMMMMMMMMMMMMk.           ...dWMMMMMMMMMMMMMMMMMWWNX0Oxol:,....  ..   ..                  ..':dOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo:'....      . .  .  ..    ..  .   .....,;clodxkO0KXNNWWMMMMMk.           . .dWMMMMWWWNXXK0Okdolc:,'....   ..        ..       .    .. ...;lkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKko:'..     .  ..  ..                  .. ......'',;:cclloo:..           ..;oollcc:;,''......                   .  .     .  .   ...;lxKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkdc,...       .                 ..   ..  ..        . .              .  .    ..  .. ...                     .  .     .. ..,:okKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0ko:,..                       ...   ....       .  .                .      ..    ...                    .  .   ..':lx0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0koc,.......      .....   .. ..   .     ....                ..      ... ..      .         ..    .  ...,:lx0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxoc;'...   .  ..   .. .  .        ..   ..        .    ..   .    ....      ..  ..    .....,:ldOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kdoc;,.....  .. .    ...   .....                      ...   .          ....';cldk0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXK0kxolc:,'....... ..... .....          ..    ..      ......',;:lodkOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0Okkxdoolcc::;,,,''''''''''''',,,;;:ccllodxxkO0KXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNXXXXXXXXXXXXXXXNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

 */

contract Degen is
    ERC721Sequential,
    ReentrancyGuard,
    Ownable,
    PaymentSplitter
{
    using Strings for uint256;
    using ECDSA for bytes32;
    mapping(bytes => uint256) private usedTickets;
    string public baseTokenURI;
    uint256 public startPresaleDate = 1685700165;
    uint256 public startMintDate = 1685786565;
    uint256 public constant MAX_SUPPLY = 999;
    uint256 public constant MINT_PRICE = 0.069 ether;
    uint256 public constant MAX_PURCHASE_COUNT = 9;
    address private presaleSigner;
    address private staffSigner;
    address private degenSigner;

    constructor(
        uint256 _startPresaleDate,
        uint256 _startMintDate,
        string memory _baseTokenURI,
        address _presaleSigner,
        address _staffSigner,
        address _degenSigner,
        address[] memory _payees,
        uint256[] memory _shares
    )
        ERC721Sequential("DEGEN", "DEGEN")
        PaymentSplitter(_payees, _shares)
    {
        startPresaleDate = _startPresaleDate;
        startMintDate = _startMintDate;
        baseTokenURI = _baseTokenURI;
        presaleSigner = _presaleSigner;
        staffSigner = _staffSigner;
        degenSigner = _degenSigner;
    }

    function mint(uint256 numberOfTokens, bytes memory pass)
        public
        payable
        nonReentrant
    {
        if (
            startPresaleDate <= block.timestamp &&
            startMintDate > block.timestamp
        ) {
            uint256 mintablePresale = validateTicket(pass);
            require(
                numberOfTokens <= mintablePresale,
                "DEGEN: Minting Too Many Presale"
            );
            useTicket(pass, numberOfTokens);
        } else {
            require(startMintDate <= block.timestamp, "DEGEN: Sale Not Started");
            require(
                numberOfTokens <= MAX_PURCHASE_COUNT,
                "DEGEN: Minting Too Many"
            );
        }

        require(totalMinted() + numberOfTokens <= MAX_SUPPLY, "DEGEN: Sold Out");

        require(
            msg.value >= numberOfTokens * MINT_PRICE,
            "DEGEN: Insufficient Payment"
        );

        for (uint256 i = 0; i < numberOfTokens; i++) {
            _safeMint(msg.sender);
        }
    }

    function _baseURI() internal view virtual override returns (string memory) {
        return baseTokenURI;
    }

    function getHash() internal view returns (bytes32) {
        return keccak256(abi.encodePacked("DEGEN", msg.sender));
    }

    function recover(bytes32 hash, bytes memory signature)
        internal
        pure
        returns (address)
    {
        return hash.toEthSignedMessageHash().recover(signature);
    }

    function validateTicket(bytes memory pass) internal view returns (uint256) {
        bytes32 hash = getHash();
        address signer = recover(hash, pass);
        uint256 mintablePresale;
        if (signer == presaleSigner) {
            mintablePresale = 1;
        } else if (signer == staffSigner) {
            mintablePresale = 5;
        } else if (signer == degenSigner) {
            mintablePresale = 50;
        } else {
            revert("DEGEN: Presale Invalid");
        }
        require(usedTickets[pass] < mintablePresale, "DEGEN: Presale Used");
        return mintablePresale - usedTickets[pass];
    }

    function useTicket(bytes memory pass, uint256 quantity) internal {
        usedTickets[pass] += quantity;
    }

    function setBaseURI(string memory _baseTokenURI) external onlyOwner {
        baseTokenURI = _baseTokenURI;
    }

    function setStartPresaleDate(uint256 _startPresaleDate) external onlyOwner {
        startPresaleDate = _startPresaleDate;
    }

    function setStartMintDate(uint256 _startMintDate) external onlyOwner {
        startMintDate = _startMintDate;
    }

    function withdraw(address payable account) public virtual {
        release(account);
    }

    function withdrawERC20(IERC20 token, address to) external onlyOwner {
        token.transfer(to, token.balanceOf(address(this)));
    }
}
/* Experimental Contract, Use At Your Own Risk */
